dbt_projet:
  target: dev
  outputs:
    dev:
      type: mysql
      server: [localhost]
      port: [3306]  # optional
      database: [my_dbt_db] # optional, should be same as schema
      schema: [schema]
      username: [root]
      password: [MysqL31!!]
      driver: MySQL ODBC 8.0 ANSI Driver
    prod:
      type: mysql
      server: [localhost]
      port: [3306]  # optional
      database: [my_dbt_db] # optional, should be same as schema
      schema: [schema]
      username: [root]
      password: [MysqL31!!]
      driver: MySQL ODBC 8.0 ANSI Driver
